# Macro file for example B5
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize
#
# Defaults:
# armAngle 30. deg
# field value: 1.0*tesla
/B5/generator/momentum 2. MeV
/B5/generator/sigmaMomentum 0. 
/B5/generator/sigmaAngle 0.
/B5/generator/sigmaAngle 2. deg
/run/beamOn 100 

